title:              오리부리
email:              almondshin8@gmail.com
description:        동물탐정 오리
author:             Almondshin
baseurl:            "/"
url:                "https://almondshin.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    almondshin
#facebook_username:  StartBootstrap
instagram_username: almond_shin
#linkedin_username: almondshin8

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
